#!/usr/bin/env bash
# Cross-compiles WheelDrive.asi with llvm-mingw (https://github.com/mstorsjo/llvm-mingw).
#   ./build.sh            build only
#   ./build.sh install    build and copy into the game folder ($GTA5_DIR)
#
# Toolchain: x86_64-w64-mingw32-clang++ and llvm-dlltool on PATH, or LLVM_MINGW=/path/to/llvm-mingw.
set -euo pipefail
cd "$(dirname "$0")"

BIN="${LLVM_MINGW:+$LLVM_MINGW/bin/}"
CXX="${BIN}x86_64-w64-mingw32-clang++"
DLLTOOL="${BIN}llvm-dlltool"
for tool in "$CXX" "$DLLTOOL"; do
    command -v "$tool" >/dev/null || { echo "missing $tool (set LLVM_MINGW or add llvm-mingw/bin to PATH)" >&2; exit 1; }
done

mkdir -p build
# Embed WheelDrive.ini as the defaults the plugin writes on first launch.
{
    echo '// Generated by build.sh from WheelDrive.ini. Do not edit.'
    printf '%s' 'static const char* kDefaultIni = R"WDINI('
    cat WheelDrive.ini
    echo ')WDINI";'
} > build/default_ini.h

"$DLLTOOL" -m i386:x86-64 -D ScriptHookV.dll -d src/ScriptHookV.def -l build/libScriptHookV.a
"$CXX" -std=c++20 -O2 -shared -static -s -Wall -Ibuild -Wl,--no-insert-timestamp \
    -o build/WheelDrive.asi src/WheelDrive.cpp \
    build/libScriptHookV.a -ldinput8 -ldxguid -lshell32 -luser32
echo "built build/WheelDrive.asi"

if [[ "${1:-}" == install ]]; then
    : "${GTA5_DIR:?set GTA5_DIR to the folder containing GTA5_Enhanced.exe or GTA5.exe}"
    cp build/WheelDrive.asi "$GTA5_DIR/"
    echo "installed to $GTA5_DIR"
fi
